/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coursoemvideo.operacao;

/**
 *
 * @author Ronaldo
 */
public class TelaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() { // Contrutor - e o metodo com mesmo nome da classe
        initComponents();
        jPanel_calculo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bto_Calcular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_Numero = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jPanel_calculo = new javax.swing.JPanel();
        txt_absoluto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_raizcubica = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_raizquadrada = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cubo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_resto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Super Calculadora");

        bto_Calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculos.png"))); // NOI18N
        bto_Calcular.setText("Calcular");
        bto_Calcular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 255, 204), null, null));
        bto_Calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bto_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_CalcularActionPerformed(evt);
            }
        });

        jLabel2.setText("Informe um valor:  ");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculadoragrande.png"))); // NOI18N

        txt_absoluto.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        txt_absoluto.setForeground(new java.awt.Color(0, 0, 204));

        jLabel8.setText("Valor Absoluto");

        txt_raizcubica.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        txt_raizcubica.setForeground(new java.awt.Color(0, 0, 204));
        txt_raizcubica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_raizcubicaActionPerformed(evt);
            }
        });

        jLabel7.setText("Raiz Cúbica");

        txt_raizquadrada.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        txt_raizquadrada.setForeground(new java.awt.Color(0, 0, 204));

        jLabel6.setText("Raiz Quadrada");

        txt_cubo.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        txt_cubo.setForeground(new java.awt.Color(0, 0, 204));

        jLabel5.setText("Elevado ao cubo");

        txt_resto.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        txt_resto.setForeground(new java.awt.Color(0, 0, 204));
        txt_resto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_restoActionPerformed(evt);
            }
        });

        jLabel4.setText("Resto da divisão por 2");

        javax.swing.GroupLayout jPanel_calculoLayout = new javax.swing.GroupLayout(jPanel_calculo);
        jPanel_calculo.setLayout(jPanel_calculoLayout);
        jPanel_calculoLayout.setHorizontalGroup(
            jPanel_calculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_calculoLayout.createSequentialGroup()
                .addGroup(jPanel_calculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_calculoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_calculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel_calculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_raizcubica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txt_raizquadrada, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_cubo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_resto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_absoluto)))
        );
        jPanel_calculoLayout.setVerticalGroup(
            jPanel_calculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_calculoLayout.createSequentialGroup()
                .addGroup(jPanel_calculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_resto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(19, 19, 19)
                .addGroup(jPanel_calculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cubo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel_calculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_raizquadrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel_calculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_raizcubica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel_calculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txt_absoluto))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel_calculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bto_Calcular))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bto_Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jPanel_calculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_restoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_restoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_restoActionPerformed

    private void txt_raizcubicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_raizcubicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_raizcubicaActionPerformed

    private void bto_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_CalcularActionPerformed
        // TODO add your handling code here:
        jPanel_calculo.setVisible(true);
        int valor = Integer.parseInt(txt_Numero.getValue().toString());
        int resto = valor % 2;
        double cubo = Math.pow(valor,3);
        double raizq = Math.sqrt(valor);
        double raizc = Math.cbrt(valor);
        int abs = Math.abs(valor);
        
        
        txt_resto.setText(Integer.toString(resto));
        txt_cubo.setText(String.format("%.0f",cubo));
        txt_raizquadrada.setText(String.format("%.2f",raizq));
        txt_raizcubica.setText(String.format("%.2f",raizc));
        txt_absoluto.setText(Integer.toString(abs));
        
    }//GEN-LAST:event_bto_CalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bto_Calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel_calculo;
    private javax.swing.JSpinner txt_Numero;
    private javax.swing.JTextField txt_absoluto;
    private javax.swing.JTextField txt_cubo;
    private javax.swing.JTextField txt_raizcubica;
    private javax.swing.JTextField txt_raizquadrada;
    private javax.swing.JTextField txt_resto;
    // End of variables declaration//GEN-END:variables
}
